### ISSUE TITLE
Cargar Respaldos (Modelos y Fuentes ya existentes)

### ISSUE THREAD

**Issue by norwis** [satus-ve/administrativo#7]
Tarea ya realizada.

**Comment by ggil** [comment]
Se puede decir que satus es la formalización del trabajo en equipo entre Atiptech y GC Tech, y que el proyecto del sistema administrativo, es una evolución de PyGekko, un proyecto fallido de GC Tech, la fuente cargada es una mezcla de ambos respaldos y trabajos realizados en su momento.... listo!
